### ISSUE TITLE
Feature Request: Support version IDs in S3 protocol

### ISSUE THREAD

**Issue by xtagon** [DarthSim/imgproxy#100]
Hi,

We are transitioning to use the S3 protocol, which is a fantastic feature for us because it eliminates some problems with cache busting since we don't have to specify breaking expiration params in the origin URL. Thanks for that feature!

However, we use S3 versioning extensively, and it's not possible to pass the version ID of an object when using the `s3://...` protocol with imgproxy. Is this something that would be easy to implement?

Thanks!

**Comment by itsliang** [comment]
If this feature is accepted, I hope it can be applied to google cloud storage as well.

**Comment by DarthSim** [comment]
Both S3 version ID and GCS generation support are added to v2.1.0.rc2 which is available on Docker Hub. Use query string of source URL to specify version/generation:

```
s3://bucket_name/file_name?version_id
```

**Comment by DarthSim** [comment]
Just released imgproxy v2.1.0 with this and other awesome features. Check out the changelog for details: https://github.com/DarthSim/imgproxy/blob/master/CHANGELOG.md#v210

**Comment by xtagon** [comment]
Thanks, that was fast!
