### ISSUE TITLE
Is there a way to accommodate error catching with Bugsnag?

### ISSUE THREAD

**Issue by xtagon** [DarthSim/imgproxy#101]
Hi,

First, thanks for imgproxy, we're transitioning to it from another solution and it's _so much_ lighter on server resources 👍 

What would you advise if we wanted to configure Bugsnag to catch unhandled errors? So far we haven't seen any problem images going through imgproxy, but when we set up other solutions we found some edge cases (like files being encoded incorrectly but still valid enough to be shown in the browser), and it would be good to use our error catching system in case of any failures.

I see there is a Go library for Bugsnag: https://github.com/bugsnag/bugsnag-go

They support net/http, but I can see imgproxy uses fasthttp which I'm not familiar with. Do you know if this could work?

Thanks!

**Comment by DarthSim** [comment]
Hi,

I added Bugsnag and Honeybadger support to `v2.1.0.rc2` which is available on Docker Hub. https://github.com/DarthSim/imgproxy/blob/version/2.1/docs/configuration.md#errors-reporting

**Comment by DarthSim** [comment]
Just released imgproxy v2.1.0 with this and other awesome features. Check out the changelog for details: https://github.com/DarthSim/imgproxy/blob/master/CHANGELOG.md#v210

**Comment by xtagon** [comment]
Thanks so much!
