### ISSUE TITLE
Enable configuring of S3 client endpoint and region

### ISSUE THREAD

**Issue by walu-lila** [DarthSim/imgproxy#103]
Most of the major cloud storage services are S3 API compatible. 
Currently the S3 client uses the default options.
By enabling the configuration of the endpoint and region of the client, imgproxy could support many more storage options.
Instead of manually adding support for each service in the code.

**Comment by DarthSim** [comment]
Hi,
You can specify region with `AWS_REGION`. Endpoint support will come with v2.1.

**Comment by DarthSim** [comment]
`v2.1.0.rc2` image is available on Docker Hub. The endpoint can be configured with `IMGPROXY_S3_ENDPOINT`.

**Comment by DarthSim** [comment]
Just released imgproxy v2.1.0 with this and other awesome features. Check out the changelog for details: https://github.com/DarthSim/imgproxy/blob/master/CHANGELOG.md#v210
