### ISSUE TITLE
Throwing errors when failing to get EXIF orientation

### ISSUE THREAD

**Issue by daneren2005** [DarthSim/imgproxy#108]
We are having an issue with some images failing to load due to missing EXIF orientation.  Looks like in https://github.com/DarthSim/imgproxy/blob/c03a9c69c385ed5c524aac980d6488f2766ae5ae/vips.h#L107 it just hard exits if it fails to grab the orientation for any reason.

The error I am getting from Bugsnag is `vips_get_exif_orientation: Can't get EXIF orientation vips_get_exif_orientation: Can't get EXIF orientation vips2png: unable to write to buffer `

A full log is:
```
imgproxy-5d577df96f-lm9dz — (imgproxy:1): VIPS-WARNING **: 20:03:49.363: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50
imgproxy-5d577df96f-lm9dz —
imgproxy-5d577df96f-lm9dz — (imgproxy:1): VIPS-WARNING **: 20:03:49.364: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50
imgproxy-5d577df96f-lm9dz —
imgproxy-5d577df96f-lm9dz — (imgproxy:1): VIPS-WARNING **: 20:03:49.370: profile 'icc': 0h: PCS illuminant is not D50
imgproxy-5d577df96f-lm9dz — 2018/11/28 20:03:49 notifying bugsnag: vips_get_exif_orientation: Can't get EXIF orientation
imgproxy-5d577df96f-lm9dz — vips_get_exif_orientation: Can't get EXIF orientation
imgproxy-5d577df96f-lm9dz — vips2png: unable to write to buffer
imgproxy-5d577df96f-lm9dz — 2018/11/28 20:03:49 |[7;31m 500 [0m| [GvxhU4btbnAgrVYiAcNRbi] vips_get_exif_orientation: Can't get EXIF orientation
imgproxy-5d577df96f-lm9dz — vips_get_exif_orientation: Can't get EXIF orientation
imgproxy-5d577df96f-lm9dz — vips2png: unable to write to buffer
imgproxy-5d577df96f-lm9dz —
```

This is probably more of a libvips issue, but there are always going to problematic images that any library will choke on.  I think it would make more sense to not hard exit in cases like this if we are able to finish processing the image without the orientation information.  I have attached an example image causing the error below.

NOTE: I am *not* a GO developer, so I may be misreading the code.

**Comment by daneren2005** [comment]
![roma photo black](https://user-images.githubusercontent.com/414653/49179637-8c5c9b00-f307-11e8-8e1f-1dc931b72c40.png)

**Comment by DarthSim** [comment]
Hi!

Thanks to catching this. There was an error in EXIF orientation detecting, but this wasn't the main thing. The image has an invalid ICC profile, and libPng can't save it. I have patched the saving process, so it will try to save the image without an embedded profile if the previous try wasn't successful.

v2.1.1 image is pushed to Docker Hub.

**Comment by daneren2005** [comment]
And it loads!  Thank you so much for this!
