### ISSUE TITLE
Can we give you a donation?

### ISSUE THREAD

**Issue by daneren2005** [DarthSim/imgproxy#109]
My company wants to give you a decent donation for all of your hard work.  ImgProxy is heads and shoulders above the server we were using before, and you have saved us a ton of time writing our own.  Can you give us a Paypal account or some way to donate you?

**Comment by DarthSim** [comment]
Wow! Thank you, I very appreciate this! 

I think PayPal would be the easiest way. My email is darthsim@gmail.com.

Could I also ask you to share your story in #62?

Thank you and good luck with your project!

**Comment by daneren2005** [comment]
Going to close this since I got the info I needed
