### ISSUE TITLE
Using imgproxy with minio as an alternative to S3

### ISSUE THREAD

**Issue by egorsmkv** [DarthSim/imgproxy#114]
I want to use imgproxy with https://github.com/minio/minio (it is an alternative to S3)

But have had some issues with this:

1) Unable to use imgproxy without setting AWS_REGION
2) By default, imgproxy sets https scheme for requests

**Comment by DarthSim** [comment]
Hi,

I made some changes in v2.1.3, now it's possible to use imgproxy with Minio. https://github.com/DarthSim/imgproxy/blob/master/docs/serving_files_from_s3.md#minio

**Comment by egorsmkv** [comment]
Just checked, works good. Thank you a lot!
