### ISSUE TITLE
Memory leaks imgproxy v2.1.3 ?

### ISSUE THREAD

**Issue by DanteG41** [DarthSim/imgproxy#116]
During the day at an average load of ~200 rpm there is a constant growth of rss memory. What memory consumption is normal for imgproxy ?  I use imgproxy v2.1.3 on bare metal with dev-lang/go-1.10.1

Settings:
```
IMGPROXY_BIND=127.0.0.1:8080
IMGPROXY_LOCAL_FILESYSTEM_ROOT=/home/project/static
IMGPROXY_ENABLE_WEBP_DETECTION=true
IMGPROXY_PROMETHEUS_BIND=127.0.0.1:9080
IMGPROXY_CONCURRENCY=10
IMGPROXY_MAX_CLIENTS=20
```
Some graphs:
![image](https://user-images.githubusercontent.com/5330084/50152411-55195280-02e5-11e9-9f86-d8484b8f5b99.png)
![image](https://user-images.githubusercontent.com/5330084/50152434-62ced800-02e5-11e9-9cf9-de2703de7e21.png)
![image](https://user-images.githubusercontent.com/5330084/50152455-74b07b00-02e5-11e9-92bc-f44dcc626de3.png)

Sample processing:
2018/12/18 16:53:46 | 200 | [P6qFfmvtKhatZE6zNCtFu5] Processed in 49.943965ms: local:///sn037/images/product/193/762/606_original.jpg; &{Resize:fill Width:200 Height:200 Dpr:1 Gravity:{Type:soea X:0 Y:0} Enlarge:false Format:webp Quality:80 Flatten:false Background:{R:255 G:255 B:255} Blur:0 Sharpen:0 CacheBuster: Watermark:{Enabled:false Opacity:1 Replicate:false Gravity:ce OffsetX:0 OffsetY:0 Scale:0} UsedPresets:[]}

libvips v8.7.2 build options:
```
native win32:                           no
native OS X:                            no
open files in binary mode:              no
enable debug:                           no
enable deprecated library components:   yes
enable docs with gtkdoc:                no
gobject introspection:                  no
enable vips7 C++ API:                   no (default)
enable vips7 Python binding:            no (default)
enable vips8 Python overrides:          no (default)
  (requires pygobject-3.13.0 or later)
enable radiance support:                yes
enable analyze support:                 yes
enable PPM support:                     yes

* optional dependencies
use fftw3 for FFT:                      no
Magick package:                         MagickCore
Magick API version:                     magick6
load with libMagick:                    yes
save with libMagick:                    yes
accelerate loops with orc:              no
  (requires orc-0.4.11 or later)
ICC profile support with lcms:          no
file import with niftiio:               no
file import with OpenEXR:               no
file import with OpenSlide:             no
  (requires openslide-3.3.0 or later)
file import with matio:                 no
PDF import with PDFium                  no
PDF import with poppler-glib:           no
  (requires poppler-glib 0.16.0 or later)
SVG import with librsvg-2.0:            no
  (requires librsvg-2.0 2.34.0 or later)
zlib:                                   yes
file import with cfitsio:               no
file import/export with libwebp:        yes
  (requires libwebp-0.1.3 or later)
support webp metadata:                  yes
  (requires libwebpmux-0.5 or later)
text rendering with pangoft2:           no
file import/export with libpng:         yes (pkg-config libpng >= 1.2.9)
  (requires libpng-1.2.9 or later)
support 8bpp PNG quantisation:          no
  (requires libimagequant)
file import/export with libtiff:        no
file import/export with giflib:         yes (found by search)
file import/export with libjpeg:        yes (pkg-config)
image pyramid export:                   no
  (requires libgsf-1 1.14.26 or later)
use libexif to load/save JPEG metadata: no
```

**Comment by DarthSim** [comment]
HI!

Sorry for the delay, I was on vacation and took a rest from imgproxy too :)

I fixed a couple of things that could cause leaks. Heap profile doesn't show anything suspicious. clang's address sanitizer doesn't detect any leaks either, but I'm not sure if it works correctly with Go.

Please check out v2.1.4.

**Comment by DanteG41** [comment]
4 days on v2.1.4 memory growth has slowed, but it looks like there is a leak. I could not find correlations with 500 errors or used image formats.

![image](https://user-images.githubusercontent.com/5330084/51107767-a0a21c00-1811-11e9-9f8a-15854fb520d3.png)

**Comment by DanteG41** [comment]
Probably memory begins to grow during the processing of corrupted images. 
`while true;do sleep 0.1;curl -I -XGET http://127.0.0.1:8080/bztest/resize:fill:200:200/gravity:soea/plain/local:///sn033/images/product/207/827/990_original.jpg;done`

![image](https://user-images.githubusercontent.com/5330084/51172063-3a320200-18d4-11e9-8120-607a432636b8.png)

Here's the corrupted image
![990_original](https://user-images.githubusercontent.com/5330084/51172460-19b67780-18d5-11e9-8621-afdf210d1727.jpg)

**Comment by DarthSim** [comment]
Thanks! I'll check this out.

I also noticed memory fragmentation that may look like a memory leak. I made some improvements and current results of stress testing look pretty optimistic. I'll check all things out and will come with results in a couple of days.

**Comment by DarthSim** [comment]
Just released v2.2. Made a couple changes to decrease memory fragmentation. Also, you may probably want to look at https://github.com/DarthSim/imgproxy/blob/master/docs/memory_usage_tweaks.md

**Comment by DarthSim** [comment]
More optimizations in v2.2.1

**Comment by DanteG41** [comment]
24h with 2.2.0, now I will try 2.2.1
![image](https://user-images.githubusercontent.com/5330084/51533832-ceb4db00-1e65-11e9-9408-60a93650ffed.png)

**Comment by DarthSim** [comment]
That's pretty weird. I don't see anything like this on our servers. Stress tests also show stable memory usage without constant growth.

I noticed that you built libvips with the support of loading with libMagick. Could you try to build it with `--disable-magickload`? If you're not going to support GIF files it's better to disable libMagick support at all.

**Comment by DarthSim** [comment]
Do you collect `go_memstats_sys_bytes`, `go_memstats_heap_inuse_bytes` and `go_memstats_heap_idle_bytes`? I'd like to look at them stats.

**Comment by DanteG41** [comment]
v2.2.1 with disable-magickload
![image](https://user-images.githubusercontent.com/5330084/51655534-fb303a80-1fbe-11e9-82e2-2904d99a3c18.png)
![image](https://user-images.githubusercontent.com/5330084/51655554-084d2980-1fbf-11e9-8b84-44d2b574e250.png)

**Comment by DanteG41** [comment]
today I'll try without libmagick
```
* build options
native win32:				no
native OS X:				no
open files in binary mode: 		no
enable debug:				no
enable deprecated library components:	yes
enable docs with gtkdoc:		no
gobject introspection: 			no
enable vips7 C++ API: 			no (default)
enable vips7 Python binding:		no (default)
enable vips8 Python overrides:		no (default)
  (requires pygobject-3.13.0 or later)
enable radiance support: 		yes
enable analyze support: 		yes
enable PPM support: 			yes

* optional dependencies
use fftw3 for FFT: 			no
Magick package: 			none
Magick API version: 			none
load with libMagick: 			no
save with libMagick: 			no
accelerate loops with orc: 		no
  (requires orc-0.4.11 or later)
ICC profile support with lcms: 		no
file import with niftiio: 		no
file import with OpenEXR: 		no
file import with OpenSlide:		no
  (requires openslide-3.3.0 or later)
file import with matio: 		no
PDF import with PDFium 			no
PDF import with poppler-glib: 		no
  (requires poppler-glib 0.16.0 or later)
SVG import with librsvg-2.0: 		no
  (requires librsvg-2.0 2.34.0 or later)
zlib: 					yes
file import with cfitsio: 		no
file import/export with libwebp:	yes
  (requires libwebp-0.1.3 or later)
support webp metadata:			yes
  (requires libwebpmux-0.5 or later)
text rendering with pangoft2: 		no
file import/export with libpng: 	yes (pkg-config libpng >= 1.2.9)
  (requires libpng-1.2.9 or later)
support 8bpp PNG quantisation:		no
  (requires libimagequant)
file import/export with libtiff:	no
file import/export with giflib:		yes (found by search)
file import/export with libjpeg:	yes (pkg-config)
image pyramid export:			no
  (requires libgsf-1 1.14.26 or later)
use libexif to load/save JPEG metadata: no
```

**Comment by DarthSim** [comment]
Well, Go's stats look stable as expected. Looks like it's CGO part

**Comment by DanteG41** [comment]
v2.2.1 without libMagick and rebuild with go 1.10.7. all the same
![image](https://user-images.githubusercontent.com/5330084/51731048-85e66780-209b-11e9-9348-e7df5496cb2a.png)

**Comment by DanteG41** [comment]
v2.2.2
![image](https://user-images.githubusercontent.com/5330084/52201706-1851ec80-288e-11e9-9f52-ee8dfd8a82a1.png)

**Comment by DarthSim** [comment]
Since you have a huge rpm, try to increase `IMGPROXY_BUFFER_POOL_CALIBRATION_THRESHOLD`. It's 1024 by default and this means that buffer pools are calibrated too often on your load. Let's try something around 8192.

Also it may be useful to look at the following stats:
`max(buffer_default_size_bytes{app="$application"}) by (type)`
`max(buffer_max_size_bytes{app="$application"}) by (type)`

**Comment by DanteG41** [comment]
restarted with
```
IMGPROXY_BIND=127.0.0.1:8080
IMGPROXY_LOCAL_FILESYSTEM_ROOT=/home/project/static
IMGPROXY_ENABLE_WEBP_DETECTION=true
IMGPROXY_PROMETHEUS_BIND=127.0.0.1:9080
IMGPROXY_CONCURRENCY=10
IMGPROXY_MAX_CLIENTS=20
IMGPROXY_FREE_MEMORY_INTERVAL=1
IMGPROXY_DOWNLOAD_BUFFER_SIZE=153600
IMGPROXY_MAX_SRC_FILE_SIZE=10485760
IMGPROXY_LOG_MEM_STATS=1
IMGPROXY_BUFFER_POOL_CALIBRATION_THRESHOLD=8192
```

**Comment by DarthSim** [comment]
Noticed that you're using local files serving. I replaced filesystem transport with a self-made simpler version in v2.2.3. Maybe it'll help.

**Comment by DanteG41** [comment]
v2.2.3
![image](https://user-images.githubusercontent.com/5330084/52416762-29a82c80-2b0c-11e9-96f2-eae4ed5a8d1c.png)

**Comment by DarthSim** [comment]
Well, I'm literally out of ideas. Our instances go on their average memory usage for a long time. Let's collect some more info about your installation:

* What's your latest `libvips` config?
* Could you build `libvips` with `fftw3` and `orc`?
* Do you use `libjpeg` or `libjpeg-turbo`? `libjpeg-turbo` is recommended.

Let's also take a look at some stats:

* Latest Go memstats. Need to ensure it doesn't grow unexpectedly;
* `buffer_default_size_bytes` and `buffer_max_size_bytes`.
* `go_goroutines` and `go_threads`. Need to ensure they we don't leak goroutines;
* `errors_total` rate by type.

**Comment by DanteG41** [comment]
* current libvips config:
```
* build options
native win32: no
native OS X: no
open files in binary mode: no
enable debug: no
enable deprecated library components: yes
enable docs with gtkdoc: no
gobject introspection: no
enable vips7 C++ API: no (default)
enable vips7 Python binding: no (default)
enable vips8 Python overrides: no (default)
(requires pygobject-3.13.0 or later)
enable radiance support: yes
enable analyze support: yes
enable PPM support: yes

* optional dependencies
use fftw3 for FFT: yes
Magick package: none
Magick API version: none
load with libMagick: no
save with libMagick: no
accelerate loops with orc: no
(requires orc-0.4.11 or later)
ICC profile support with lcms: no
file import with niftiio: no
file import with OpenEXR: no
file import with OpenSlide: no
(requires openslide-3.3.0 or later)
file import with matio: no
PDF import with PDFium no
PDF import with poppler-glib: no
(requires poppler-glib 0.16.0 or later)
SVG import with librsvg-2.0: no
(requires librsvg-2.0 2.34.0 or later)
zlib: yes
file import with cfitsio: no
file import/export with libwebp: yes
(requires libwebp-0.1.3 or later)
support webp metadata: yes
(requires libwebpmux-0.5 or later)
text rendering with pangoft2: no
file import/export with libpng: yes (pkg-config libpng >= 1.2.9)
(requires libpng-1.2.9 or later)
support 8bpp PNG quantisation: no
(requires libimagequant)
file import/export with libtiff: no
file import/export with giflib: yes (found by search)
file import/export with libjpeg: yes (pkg-config)
image pyramid export: no
(requires libgsf-1 1.14.26 or later)
use libexif to load/save JPEG metadata: no
```
* current config with fftw. build libvips with orc has crash run https://pastebin.com/raw/GXjfm7rg
* Uses: dev-libs/libvips-8.7.4 media-libs/libjpeg-turbo-1.5.1 dev-lang/go-1.10.7 www-servers/imgproxy-2.2.3
* memstats 
![image](https://user-images.githubusercontent.com/5330084/53802164-f3bb6400-3f62-11e9-9a8c-6e89aa1d055c.png)
* buffer_default_size_bytes and buffer_max_size_bytes. do you mean IMGPROXY_DOWNLOAD_BUFFER_SIZE IMGPROXY_MAX_SRC_FILE_SIZE ?
* go_goroutines and go_threads - how can I get these metrics ?
* 500 errors by file type
![image](https://user-images.githubusercontent.com/5330084/53802397-8fe56b00-3f63-11e9-8310-b7fb0d0a6c7d.png)
* rss and rpm
![image](https://user-images.githubusercontent.com/5330084/53802580-f5395c00-3f63-11e9-8ba2-228ad4859f32.png)

**Comment by DarthSim** [comment]
`buffer_default_size_bytes `, `buffer_max_size_bytes `, `go_goroutines`, and `go_threads` are Prometheus metrics. As far as I understand, you use Prometheus.

If it's possible, could you set `IMGPROXY_VIPS_LEAK_CHECK=1` to enable libvips internal leak checking? It will print leaked objects on imgproxy shutdown.

It's very suspicious that RSS usage doesn't go down at all. Can I know your kernel version?

**Comment by DanteG41** [comment]
kernel 4.4.127-gentoo-universal-04

**Comment by DanteG41** [comment]
![buffer](https://user-images.githubusercontent.com/5330084/53973597-e351e780-4122-11e9-9443-2db6befa897e.png)
![go_stats](https://user-images.githubusercontent.com/5330084/53973599-e3ea7e00-4122-11e9-8e8d-30eb55009e45.png)
![rss](https://user-images.githubusercontent.com/5330084/53973600-e3ea7e00-4122-11e9-80d8-b315699b33bd.png)
![vips](https://user-images.githubusercontent.com/5330084/53973601-e3ea7e00-4122-11e9-8d9c-a0da3001ddd5.png)

**Comment by DanteG41** [comment]
![image](https://user-images.githubusercontent.com/5330084/54115451-45099e80-440e-11e9-8454-e97eca21e6ce.png)
![image](https://user-images.githubusercontent.com/5330084/54115469-4d61d980-440e-11e9-855e-215c1103cf23.png)
![image](https://user-images.githubusercontent.com/5330084/54115478-53f05100-440e-11e9-8965-1826ca2eec35.png)
![image](https://user-images.githubusercontent.com/5330084/54115491-5a7ec880-440e-11e9-826f-af6a20464851.png)

```
# imgproxy -v
2.2.6
# grep VIPS <(env)
IMGPROXY_VIPS_LEAK_CHECK=1
 ^C
2019/03/11 15:00:55 Shutting down the server...
2019/03/11 15:00:55 [MaeTxrtfUIjhz84gMxPafi] | 200 | Processed in 56.081757ms: local:///sn014/images/product/241/763/945_original.jpg; &{Resize:fill Width:200 Height:200 Dpr:1 Gravity:{Type:soea X:0 Y:0} Enlarge:false Expand:false Format:webp Quality:80 Flatten:false Background:{R:255 G:255 B:255} Blur:0 Sharpen:0 CacheBuster: Watermark:{Enabled:false Opacity:1 Replicate:false Gravity:ce OffsetX:0 OffsetY:0 Scale:0} UsedPresets:[]}
2019/03/11 15:00:55 [MEMORY USAGE] Sys: 87; HeapIdle: 63; HeapInuse: 13
memory: high-water mark 98.63 MB
```
![image](https://user-images.githubusercontent.com/5330084/54115818-2ce64f00-440f-11e9-8046-8599a097da00.png)

**Comment by DanteG41** [comment]
it is very similar that the processing of these images increases memory.
processing of the images returns error 
```
Unexpected error: vips2png: unable to write to buffer
Unexpected error: VipsJpeg: Corrupt JPEG data: premature end of data segment
```
[img.zip](https://github.com/DarthSim/imgproxy/files/2987733/img.zip)

**Comment by DarthSim** [comment]
Well, Go's and Vips' mem stats look pretty normal, and I still don't see any correlation between broken images and memory growth on my instances. Let's dig deeper and try to tune GLib. I've tried two options and both shown very good results:

The first one is to run imgproxy with `MALLOC_ARENA_MAX=4`. This will reduce GLib's appetites. You can read more [here](https://www.ibm.com/developerworks/community/blogs/efdcc4d6-e52d-4591-baf2-3f280af4795d/entry/How_to_tune_memory_allocator_on_Linux_to_achieve_best_performances_when_running_multithreaded?lang=en).

The second one is to use jemalloc. It can be used without rebuilding things, just preload its library with  `LD_PRELOAD `.

**Comment by DanteG41** [comment]
with setting MALLOC_ARENA_MAX no visible changes.
Going to jemalloc solved the problem

![image](https://user-images.githubusercontent.com/5330084/55135570-d9356e80-514d-11e9-80f1-5a37647c0d1f.png)

**Comment by DarthSim** [comment]
That looks great! Added info about `MALLOC_ARENA_MAX` and jemalloc to [memory usage tweaks guide](https://github.com/DarthSim/imgproxy/blob/master/docs/memory_usage_tweaks.md).

Do you think we may close the issue now?

**Comment by DanteG41** [comment]
Certainly. many thanks

**Comment by DarthSim** [comment]
Wow, it feels like a whole epoch past out :)

I'd be very appreciated if you could spend some time filling our [survey form](https://evilmartians.typeform.com/to/A0OfqB)
