### ISSUE TITLE
Add Description of imgproxy-form repo and local-install

### ISSUE THREAD

**Issue by mz-bmcqueen** [DarthSim/imgproxy#12]
Folks with creds won't want to push their creds to the imgproxy-form out on the net.  Add a section to the Readme describing how to clone that thing locally and use it.  Or maybe just mention it so folks can easily swipe that code to put up their own url generators.

For ref:

https://github.com/progapandist/imgproxy-form

Easy task for the eager!

**Comment by vosmith** [comment]
This issue seems to be more appropriate for the imgproxy-form repository.  Can we move it there and close this one?

**Comment by mz-bmcqueen** [comment]
It looked like the imgproxy-form repo was owned by some other project. It looks like these two belong together, and imgproxy-form might fight as an example UI in this project.

**Comment by vosmith** [comment]
Yes they are definitely related, but the change to the Readme seems like it should be done on the imgproxy-form project.

**Comment by DarthSim** [comment]
imgproxy-form is a kind of easy-test thing. Its goal is to give an ability to try your fresh deployment to Heroku without writing any code. Like press the button, fill the form, wow, it works! You totally shouldn't use it in production in any way. It's related only to [the article](https://evilmartians.com/chronicles/introducing-imgproxy), and I don't think we should mention it itself in the Readme.
On the other hand, it's absolutely safe. There is no communication between the form and any backend, even with your imgproxy instance. You can see this in its JS source.
