### ISSUE TITLE
Support for logging errors to Sentry

### ISSUE THREAD

**Issue by koenpunt** [DarthSim/imgproxy#125]
As an alternative to New Relic it would be nice to also support Sentry. 

I could take a stab at implementing this, but I'm not that experienced with Go, and I currently probably don't have time for it..

Documentation: https://docs.sentry.io/clients/go/

**Comment by DarthSim** [comment]
Hi!

There shouldn't be much of work and it's a good chance to get some Go experience :) All errors reporting is done here https://github.com/DarthSim/imgproxy/blob/master/errors_reporting.go. If you could find some time for implementing this, I would really appreciate this.

**Comment by koenpunt** [comment]
I'm looking into it now, and I have a question; The Sentry client already supports setup using environment variables (a default client is created using them when the library is included), but I'm not sure if we want to rely on that from within imgproxy, or that I should create a dedicated client, and pass in configuration from the imgproxy config. WDYT?
