### ISSUE TITLE
libMagickCore-6.Q16.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by boyfox** [DarthSim/imgproxy#133]
In the documentation, also in the change log files not provided what imagemagick version will use current release version of Imgproxy. Why?

I have installed version ImageMagick:
`    convert -version
	Version: ImageMagick 6.9.10-23 Q16 x86_64 2019-01-02 https://imagemagick.org
	Copyright: © 1999-2019 ImageMagick Studio LLC
	License: https://imagemagick.org/script/license.php
	Features: Cipher DPC Modules OpenMP 
	Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype gslib gvc jbig jng jp2 jpeg lcms ltdl lzma openexr pangocairo png ps raw rsvg tiff webp wmf x xml zlib
`

bu when i run imgproxy it calls to old version:

`./imgproxy: error while loading shared libraries: libMagickCore-6.Q16.so.5: cannot open shared object file: No such file or directory`

How can I fix it, anybody know?

Thanks in advance, great library!

**Comment by boyfox** [comment]
Also anybody know how to create executable binary file for Centos from Imgproxy source file?

**Comment by DarthSim** [comment]
Hi,

It looks like OS can't find the shared lib. If you build imgproxy or any other app with dynamic linking, you can't just copy the executable to another machine without installing all the required shared libraries. You can look at `ldd ./imgproxy` output to check what's going wrong.

> Also anybody know how to create executable binary file for Centos from Imgproxy source file?

Unfortunately, usage of CGO doesn't allow to cross-build imgproxy. You could try to build it using Docker image with your target system. At least I managed to build imgproxy for Amazon Linux this way.

**Comment by boyfox** [comment]
Hi @DarthSim, Thank you quickly replying. I know need install required libraries to Imgproxy, but I don't know which versions of libraries used imgproxy inside. For example imgproxy uses library ImageMagick yes, imgproxy release version is v2.2.1 and which version of ImageMagick required to work properly imgproxy?

Error above i described appears after I updated ImageMagick to version of 6.9.10-23 Q16 x86_64 2019-01-02 and it core so file name is libMagickCore-6.Q16.so.6. But, when i run current installed imgproxy version it asked libMagickCore-6.Q16.so.5. Then I install again old version of ImageMagick and works fine.

**Comment by boyfox** [comment]
And about building executable file from source of imgproxy, to do it I need install "golang" and libvisp library then build imgproxy file with "golang" yes?

**Comment by boyfox** [comment]
@DarthSim thank you for clearly definition and for great library! imgproxy not exists yet in yum repository and I will rebuild imgproxy with golang every time when updating dependencies.
