### ISSUE TITLE
Resize and fill

### ISSUE THREAD

**Issue by mike-hart** [DarthSim/imgproxy#139]
So far I'm loving almost everything about this as a possible replacement for an older service, especially the speed, thank you.

The resize "fit" option with background specified will fit to one of the given axes, and make the other smaller. Is there a mechanism where it will fit/scale to fill the given height/width and fill the remaining space with the background colour?

For example, given the attached image and fit:645:430:0/background:255:255:255 is there a way to ensure the outcome is a 645x430 image where the background fills the remaining space, rather than a 573x430 image with no exposed background?
![538b739993e45abe1ec0e8fc0817d724be7bedec](https://user-images.githubusercontent.com/4129199/53091487-f7360080-3509-11e9-879d-1ecf04b79c48.jpg)

**Comment by DarthSim** [comment]
Hi,

I added [extend](https://github.com/DarthSim/imgproxy/blob/master/docs/generating_the_url_advanced.md#extend) option to v2.2.5.

I'd be very appreciated if you could spend some time filling our [survey form](https://evilmartians.typeform.com/to/A0OfqB)
