### ISSUE TITLE
imgproxy doesn't rotate jpegs according to EXIF neither keeps EXIF

### ISSUE THREAD

**Issue by homm** [DarthSim/imgproxy#14]
Some images should be displayed in the different orientation than physically stored in the file. This information is stored in Orientation EXIF tag.

imgproxy doesn't rotate the processed image according to EXIF and also strips EXIF completely from result images including orientation tag.

Most browsers nowadays [don't respect that tag](https://developer.mozilla.org/ru/docs/Web/CSS/image-orientation#Browser_compatibility) and don't rotate images, so someone should do it.

**Comment by DarthSim** [comment]
Good point! Will add this feature shortly.

**Comment by christophmegusta** [comment]
if you could add rotation, cropping by area feature to this nice project we could replace our inhouse solution with it.

**Comment by DarthSim** [comment]
The latest version of imgproxy rotates images according to their EXIF orientation tag.
