### ISSUE TITLE
GCS sources losing query string

### ISSUE THREAD

**Issue by molfar** [DarthSim/imgproxy#141]
I need to server files from GCS and have nice image urls at the same time. 

I set IMGPROXY_BASE_URL=gs:// and in image url I pass relative bucket path, like /bucketname/imagename.jpg - and everything works fine. 

We have nice urls like https://img.site.com/t1ByB_s/pr:medium/plain/bucketname/imagename.jpg?seed=123

But the problem is that in such case imgproxy does not pass query string to GCS, and as result - it gets stale (cached) content from there.

Expected: gs:///bucketname/imagename.jpg?seed=123
But got: gs:///bucketname/imagename.jpg

**Comment by DarthSim** [comment]
First of all, you need to escape source URLs that have query strings (read [here](https://github.com/DarthSim/imgproxy/blob/master/docs/generating_the_url_advanced.md#source-url)).

What `seed` param is for? If you try to specify a file generation, it should be `gs:///bucketname/imagename.jpg?123` (read [here](https://github.com/DarthSim/imgproxy/blob/master/docs/serving_files_from_google_cloud_storage.md)).

imgproxy receives files from GCS through API, so it doesn't send any query params.

**Comment by molfar** [comment]
If I use plain path, according to template
/%bucket_name/%file_key?%generation
Should I encoded question mark in url?

**Comment by DarthSim** [comment]
Yep, it's still a part of the source URL/

**Comment by molfar** [comment]
Calculating signature should be with encoded question mark (%3F) - or raw (?) ?

**Comment by DarthSim** [comment]
Ugh, v2.2.5 contains a bug that checks the signature using unescaped source URL. Will be fixed in v2.2.6.

**Comment by DarthSim** [comment]
I'd be very appreciated if you could spend some time filling our [survey form](https://evilmartians.typeform.com/to/A0OfqB)

**Comment by molfar** [comment]
I deleted my comment because I thought it was my mistake about encoding question mark. Im glad to help catch this bug.
