### ISSUE TITLE
Why imgproxy gets cached (stale) image from GCS?

### ISSUE THREAD

**Issue by molfar** [DarthSim/imgproxy#142]
We use GCS as storage for source images. When our app replace source image in storage bucket, without changing its filename - imgproxy does not "see" the new image, and continues generate versions from old source.

**Comment by DarthSim** [comment]
imgproxy doesn't do any caching under the hood. Basically, it gets the same data as cURL would get. If you have any cache in front of imgproxy (as far as I remember from the survey, you do have one), it may be the source of your problem. Since your URL wasn't changed, caching server returns the latest cached response. If an image filename doesn't change on upload, I'd recommend using [cache buster](https://github.com/DarthSim/imgproxy/blob/master/docs/generating_the_url_advanced.md#cache-buster) option or GCS versioning.

**Comment by molfar** [comment]
@DarthSim You know, we really have Google CDN in front of imgproxy. I checked the logs of CDN, and it shows requests to backend (imgproxy) after changing source image (with the same filename). 

For debug purposes I add random query string to url to bypass CDN cache. But imgproxy itself "cant" fetch the updated image from GCS, and continues processing old version (staled) of these image. 

Again, I checked CDN logs for this. After about an hour imgproxy starts to process the new version of source image.

**Comment by DarthSim** [comment]
Can't reproduce the issue on the test GCS bucket. Does it reproduce if you call imgproxy directly (without CDN)?

**Comment by molfar** [comment]
Checked with disabled Google Cloud CDN - issue still exists. 
I noticed that image is cached with GCS image's api public url like https://storage.googleapis.com/somebucket/vectors/cats/3248-test.png
When I try to bypass it with some random query string https://storage.googleapis.com/somebucket/vectors/cats/3248-test.png?seed=123 - it shows the new version of changed (updated) image file.

**Comment by DarthSim** [comment]
Do you use `gs://...` URL or `https://...` one?

**Comment by molfar** [comment]
In imgproxy config I set IMGPROXY_BASE_URL=gs:// and of course set IMGPROXY_GCS_KEY.
Then I generate image url like so 
https://img.site.com/q1y66uQ/pr:medium/plain/somebucket/vectors/cats/3248-test.png
My source file stored in GCS gs://somebucket/vectors/cats/3248-test.png

**Comment by DarthSim** [comment]
Managed to reproduce the issue. Can confirm, the issue is definitely not on the imgproxy side. GCS caches public-accessible files and responds with cached versions even when files are requested via API. Since this is the issue with GCS behavior, I can't do anything here.

**Comment by adinvadim** [comment]
I have the same problem. You still don't have a cache under the hood?

**Comment by DarthSim** [comment]
As I said before, the problem is on the GCS side, and it doesn't look like we can bypass it on the imgproxy side. GCS caches publically accessible objects, here's the explanation: https://cloud.google.com/storage/docs/caching
