### ISSUE TITLE
Color issues (HDR?) on resize

### ISSUE THREAD

**Issue by mike-hart** [DarthSim/imgproxy#143]
Hello,

When resizing the following the HDR-like nature of the image is "stripped". Not sure if this is the browser rendering one way and imgproxy choosing another, or something else entirely

![color_issues - original](https://user-images.githubusercontent.com/4129199/53799017-6a3f6e00-3f31-11e9-9297-1f0052f2d8a8.jpg)
![color_issues_resized](https://user-images.githubusercontent.com/4129199/53799055-817e5b80-3f31-11e9-847b-f5984456e276.jpg)

&{Resize:fit Width:1024 Height:768 Dpr:1 Gravity:{Type:ce X:0 Y:0} Enlarge:false Expand:false Format:jpeg Quality:75 Flatten:true Background:{R:255 G:255 B:255} Blur:0 Sharpen:0 CacheBuster: Watermark:{Enabled:false Opacity:1 Replicate:false Gravity:ce OffsetX:0 OffsetY:0 Scale:0}
(version 2.2.6)

**Comment by DarthSim** [comment]
Hi!
Thanks for pointing on this. Fixed in 2.2.7.

**Comment by DarthSim** [comment]
Not sure I didn't ask you about this :) , but I'd be very appreciated if you could spend some time filling our [survey form](https://evilmartians.typeform.com/to/A0OfqB)

**Comment by mike-hart** [comment]
Already done, thanks :)

**Comment by DarthSim** [comment]
Sorry for bothering. Thanks!
