### ISSUE TITLE
Filters support

### ISSUE THREAD

**Issue by jaymecd** [DarthSim/imgproxy#19]
Have you considered to add filters support? 

At least `sharpen` would make sense, as proxied image with reduced dimension is always blurry due to the compression algorithm.

**Comment by oldcai** [comment]
Have you got some samples can show sharpen can help with quality lost images?

**Comment by jaymecd** [comment]
Sure.
Origin image - http://st.motortrend.com/uploads/sites/5/2015/05/2015-Large-Luxury-SUV-front-three-quarter.jpg

![2015-large-luxury-suv-front-three-quarter](https://user-images.githubusercontent.com/824109/31047434-fb6ba75c-a60a-11e7-9587-fb2abdb61a5b.jpg)

```
$ file 2015-Large-Luxury-SUV-front-three-quarter.jpg
2015-Large-Luxury-SUV-front-three-quarter.jpg: JPEG image data, Exif standard: [TIFF image data, little-endian, direntries=0], baseline, precision 8, 2048x1360, frames 3
```

Processed image with:
```
        resize := "fill"
        width := 300
        height := 300
        gravity := "no"
        enlarge := 1
        extension := "jpg"
```

```
$ file imgproxied.jpg
imgproxied.jpg: JPEG image data, baseline, precision 8, 300x300, frames 3
```

![imgproxied](https://user-images.githubusercontent.com/824109/31047433-f0c091f0-a60a-11e7-9c6d-b91a65fcf0b3.jpg)

As you might see, `Infinity SUV` is blurred as other ones.
Hope that helps.

**Comment by DarthSim** [comment]
:tada: imgproxy v2.0 has been released :tada: Take a look at the new features, including sharpening and blur filters: https://github.com/DarthSim/imgproxy/blob/master/CHANGELOG.md#v200
