### ISSUE TITLE
Default Config and Url Formarts

### ISSUE THREAD

**Issue by oldcai** [DarthSim/imgproxy#21]
By now, more and more needs and parameters are added to the request URL, the format of  `/%signature/%resizing_type/%width/%height/%gravity/%enlarge/%encoded_url.%extension` doesn't seem capable of taking too many parameters unless extending it to a very long string.

I think a default config should be set and we only need to set size and sometimes set other parameters by keywords.

**Comment by DarthSim** [comment]
I'm going to keep the current URL format as a common way to use imgproxy, and develop a new format for a more advanced processing. But this feature is not going to appear in a short time because of my work load.

**Comment by princemaple** [comment]
Might be great to be able to define presets with a config file, then simply do `/%signature/%preset/%encoded_url.%extension`

**Comment by DarthSim** [comment]
It is totally no:

1. It is not 12factor-ready;
2. It is not simple;
3. It doesn't solve any problem.

**Comment by princemaple** [comment]
> Actually, presets aren't much related to this issue, it's better to open another one if you'd like to discuss the feature.

Cool.

**Comment by xtagon** [comment]
In my use case, changing the URL format would help with caching. If parts like the signature (we sign S3 URLs as well as imgproxy requests) could be kept in query strings, and the rest in the URL path, then we can ignore query strings on the CDN side to keep the signature from busting the cache. Has anyone else run into this? How do you solve it?

**Comment by DarthSim** [comment]
:tada: imgproxy v2.0 has been released :tada: Take a look at the new features, including new URL format, presets and default config (via presets): https://github.com/DarthSim/imgproxy/blob/master/CHANGELOG.md#v200

**Comment by princemaple** [comment]
Thanks a lot for the great works!

**Comment by mb21** [comment]
I could have sworn that at some point I saw a spec somewhat standardizing url query parameter names for image transformations and resizings, but I cannot find it anymore. Anyone heard of it and/or is this being considered for imgproxy?

**Comment by mb21** [comment]
Thanks for your reply! May I ask why it "turns more or less complex cases into a nightmare"? It seems the following [processing options](https://docs.imgproxy.net/usage/processing#processing-options) could equally be expressed as query parameters?

```
preset:sharp/resize:fill:300:400:0/gravity:sm
```

```
?preset=sharp&resizing_type=fill&width=300&height=400&enlarge=0&gravity=sm
```
