### ISSUE TITLE
Rotate after resize

### ISSUE THREAD

**Issue by jcupitt** [DarthSim/imgproxy#24]
Hello, congratulations on your nice project!

It seems to apply EXIF autorotate at the start of processing:

https://github.com/DarthSim/imgproxy/blob/master/vips.h#L176

In my opinion, it's better to do rotates near the end. If you rotate at the start, you'll force libvips to decompress the whole image into memory then rotate from that. If you rotate after shrinking, there will be less work to do, and you'll be able to stream the shrink operation. 

The libvips thumbnail operation handles it like this:

https://github.com/jcupitt/libvips/blob/master/libvips/resample/thumbnail.c#L338

1. Open image, do any shrink-on-load. Images are opened in sequential access mode, so they can be streamed and will not need much memory.

1a. It has support for linear shrinking, which you can probably skip.

2. Premultiply alpha, shrink, unpremultiply alpha, colour space transformation.

3. If there's rotation, allocate a memory buffer, run the previous stages into that, then rotate from the memory buffer. 

4. Crop, embed, and write to output.

This order should drop memory use and also reduce latency, since processing can start as soon as the compressed image data is ready, and you won't need to wait for the input image to be decoded. 

I may well have horribly misunderstood your code.

**Comment by DarthSim** [comment]
Hi! Thank you for libvips that makes imgproxy possible!

Thanks for the advice! I rewrote image processing code like you said, it gave us a huge performance boost and significant memory saving. I owe you!

**Comment by jcupitt** [comment]
Oh, no problem, glad it's useful!
