### ISSUE TITLE
PNG alpha needs premultiply / unpremultiply

### ISSUE THREAD

**Issue by jcupitt** [DarthSim/imgproxy#25]
Hello, to handle PNG alpha correctly, you need to premultiply / unpremultiply around resize operations. I think this page explains the issue very clearly:

http://entropymine.com/imageworsener/resizealpha/

You can see the logic libvips thumbnail uses here:

https://github.com/jcupitt/libvips/blob/master/libvips/resample/thumbnail.c#L398

**Comment by DarthSim** [comment]
Another great piece of advice, thanks! Implemented with fcf964f74e71f4c8fc71fa43fc171cece184c4a0
