### ISSUE TITLE
Beginner issue

### ISSUE THREAD

**Issue by Robx64** [DarthSim/imgproxy#28]
I'm  kinda confused, installed and it seems to work but (on local server it says: "request cancelled while waiting for connection (client timeout exceeded while awaiting headers)").
Is there any option to make it work on local machine ?
Before I've had an error related to the DNS, sorted it out changing DNS order but it still won't work :(

**Comment by DarthSim** [comment]
Hi! 
If you see this in the imgproxy log, it means that imgproxy can't download source image before timeout. Try out another image or try to increase timeout: `IMGPROXY_DOWNLOAD_TIMEOUT=10`

**Comment by Robx64** [comment]
Hello there, sorry for the delay but ... was extra busy :) anyway I managed to make it work and I'm really happy with that however, tried to change port, I think because of imgproxy my httpd won't work.
Is there any configuration file where I can change port and start imgproxy server not on 80 or 8080 ?

**Comment by DarthSim** [comment]
Happy to know that everything is ok :)
You can add `export IMGPROXY_BIND=:12345` to your shell profile (`.bashrc`, `.zshrc` or whatever you use). Or if you use it with Docker, you can add `ENV IMGPROXY_BIND :12345` to your Dockerfile.

**Comment by Robx64** [comment]
Yes, so far I did not tried other methods only docker and I already tried to change port that way .... still won't work.

**Comment by Robx64** [comment]
ooops sorry,  i tried just change port instead change env. So to make it clear: 
if this is my starting string: docker run -e IMGPROXY_KEY=my_key -e IMGPROXY_SALT=my_salt -p 8080:8080 -t imgproxy, what I suppose to do ?
remove 8080:8080 ? 
and add ENV IMGPROXY_BIND :new_port ? or leave 8080:8080 just add ENV IMGPROXY_BIND :new_port ?

**Comment by DarthSim** [comment]
You can map imgproxy port to any other port. Try `docker run -e IMGPROXY_KEY=my_key -e IMGPROXY_SALT=my_salt -p new_port:8080 -t imgproxy`

**Comment by Robx64** [comment]
Thank you, will try now

**Comment by Robx64** [comment]
Nope, it won't start apparently
It works fine only if port is set 8080:8080

**Comment by DarthSim** [comment]
But it's actually the way how Docker works. I made imgproxy available on another port this way. Can't figure out how to help you here.

**Comment by Robx64** [comment]
Thank you anyway :)
If I manage to solve this issue, will give a info :)

**Comment by Robx64** [comment]
Finally I found the culprit, it wasn't docker or running on 8080 port imgproxy, it was just misconfigured httpd :)
