### ISSUE TITLE
Gravity Coordinates

### ISSUE THREAD

**Issue by tmaroschik** [DarthSim/imgproxy#35]
In order to be able to replace the image rendering of TYPO3, a popular open source CMS on high volume sites, we would need a more specific focus definition instead of cardinal points.

TYPO3 stores it's focus information as floats in the following form

`{"x":1.27308888826e-16,"y":0.23441582680105,"width":1,"height":0.7659494452306}`

The focus area is defined via floats between 0 and 1 from the left top corner down to the right bottom. It is passed along the desired size and resizing type to the renderer. Would it be possible integrate that into imgproxy too?

**Comment by DarthSim** [comment]
:tada: imgproxy v2.0 has been released :tada: Take a look at the new features, including focus point gravity: https://github.com/DarthSim/imgproxy/blob/master/CHANGELOG.md#v200
