### ISSUE TITLE
Imgproxy on CentOS - vips installed, still don't work

### ISSUE THREAD

**Issue by Robx64** [DarthSim/imgproxy#38]
Guys, I've spent a quiet few minutes to install all the dependencies, required by "vips" required by Imgproxy but it still won't work.
[root@.......]# rpm -Uvh vips-8.5.8-1.el7.remi.x86_64.rpm
warning: vips-8.5.8-1.el7.remi.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 00f97f56: NOKEY
Preparing...                          ################################# [100%]
        package vips-8.5.8-1.el7.remi.x86_64 is already installed

There must be still something missing or imgproxy's requirements are very precise ?
Wrong vips ?

**Comment by Robx64** [comment]
useless :(

**Comment by DarthSim** [comment]
Sorry for so long period of silence.
I'm unfamiliar with CentOS, so I couldn't help you anyway :( Glad you managed to solve this by yourself!
