### ISSUE TITLE
Vips

### ISSUE THREAD

**Issue by Robx64** [DarthSim/imgproxy#39]
Everything works but from time to time I see this error message:  
"vips_colourspace: no known route from 'cmyk' to 'srgb'".
Any ideas what to do with it ?
vips supplied wirh imgproxy image so ..... ?
Update ? Fix ?
eventually ..... ?

**Comment by DarthSim** [comment]
Hi. Good catch! This happens when imgproxy tries to process CMYK image without an embedded profile. Fixed in the latest release (will be on docker hub soon).
