### ISSUE TITLE
Automatically convert to webp using Accept Header

### ISSUE THREAD

**Issue by cicerocomp** [DarthSim/imgproxy#4]
https://developers.google.com/speed/webp/faq#server-side_content_negotiation_via_accept_headers

**Comment by DarthSim** [comment]
I don't think this feature would fit imgproxy well. imgproxy is designed to be placed behind a CDN or caching proxy, that's why every parameter of resizing should be clearly defined. I'm not sure how a CDN will work with auto-detected formats, but I do think it will behave unexpectedly.

**Comment by cicerocomp** [comment]
I understand.

I currently use [thumbor](https://github.com/thumbor/thumbor) to do this conversion, and it does the automatic conversion.
I use akamai as CDN, and set the cache key to: "$request_uri$header_accept"
I would like to compare the performance of imgproxy against thumbor, I will do this in the future.

**Comment by DarthSim** [comment]
Since it's impossible to sign `Accept` header, such caching key allows an attacker to DDoS your server by sending requests with different header values.

**Comment by MarcBoeing** [comment]
I wonder if anyone here can lead me to a proper alternative serving webp images to supported browsers.
As far as I can understand, i need to create picture elements, where webp is the first format. This way browsers may grab webp insted if jpeg but it would double the size of the picture element.

Two questions regarding this feature request:
1) wouldn´t it be possible to make the accept header request configurable and set it to disabled as default
2) What about the "Accept-Encoding" header, isn´t it DDoS-able, too?
