### ISSUE TITLE
Feature Request: Support Images from local file system

### ISSUE THREAD

**Issue by tangentlin** [DarthSim/imgproxy#42]
We absolutely love imgproxy for its simplicity.  Currently we have an array of microservices orchestrated by dockers, and the containers all share a simple file volume so they can all access the files.

Currently to serve a thumbnail out of a file from the shared file volume, we would have to create another file http server, thus it incurs unnecessary file IO overhead because the file gets read, downloaded, read again before it is resized and served.  It would be great that *imgproxy* could provide such capacity read files from file protocol.  Thanks.

**Comment by Vasfed** [comment]
Hi! #41 has been merged, so you can take advantage of `IMGPROXY_LOCAL_FILESYSTEM_ROOT` (but only set it to a public directory that imgproxy has appropriate access to, `/` is unsafe).
