### ISSUE TITLE
Provide a statically linked binary 

### ISSUE THREAD

**Issue by noandrea** [DarthSim/imgproxy#45]
Will it possible to package imgproxy as a self contained library, so it could be easily installed updated? 

thanks!

**Comment by Vasfed** [comment]
Docker image is pretty much self-contained and similar to statically linked binaries in this aspect, plus running under docker is more convenient - no need for systemd/upstart/etc

**Comment by noandrea** [comment]
@Vasfed you are right, forget about it :)  
thanks for the reply though

**Comment by alasdairdc** [comment]
Just out of interest what modifications are required to create a static binary for this?

I attempted to create one but it failed:

```
CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-s' -v -o /usr/local/bin/imgproxy
...
_/imgproxy
./config.go:230: undefined: initVips
./download.go:71: undefined: imageType
./download.go:73: undefined: imageTypes
./download.go:76: undefined: UNKNOWN
./download.go:91: undefined: imageType
./download.go:108: undefined: imageType
./etag.go:11: undefined: processingOptions
./server.go:19: undefined: imageType
./server.go:33: undefined: processingOptions
./server.go:108: undefined: processingOptions
./download.go:76: too many errors
```

Yet creating a dynamically linked binary worked fine:

```
go build -v -o /usr/local/bin/imgproxy
golang.org/x/image/riff
github.com/matoous/go-nanoid
golang.org/x/image/vp8
golang.org/x/image/vp8l
golang.org/x/net/netutil
golang.org/x/image/webp
_/imgproxy
```

As far as my attempts have gone it appears disabling cgo breaks building.

N.B. I haven't dealt with go until now.
