### ISSUE TITLE
I tried adding a VIPS 8.5.8 to heroku but still no gif support

### ISSUE THREAD

**Issue by Chocksy** [DarthSim/imgproxy#48]
I made the app using the heroku button and then added this buildpack: https://github.com/kespry/heroku-buildpack-vips
It has VIPS 8.5.8 in there so above what the check does in the imgproxy code for gif support. Any idea why it would not work.

Here is an example of a URL i tried: https://epicpxls-imgproxy.herokuapp.com/n3jn6OCnw2FrV1sVJfCqw3mDtWFE6YDADRE-6H4KbcU/fill/300/300/no/1/aHR0cHM6Ly9pdGVt/cy5lcGljcHhscy5j/b20vc2hyaW5lL2Nh/Y2hlLzYwMjJkNTEx/ZmIxMmQ3Y2QyOGI5/MGJmMjdiZGFkNzEw/LmdpZg.gif

**Comment by DarthSim** [comment]
It looks like vips is built without gif support

**Comment by DarthSim** [comment]
I rewrote Heroku button. Now it deploys imgproxy to Heroku using Docker image, which supports all image types supported by imgproxy.

**Comment by Chocksy** [comment]
@DarthSim thanks a lot for the fast reply. I still get Invalid image url for what ever reason. 
Here is the example code i used:
```ruby
require "openssl"
require "base64"

key = ["c84285e0bec255fe163410fcedfe61e256f04a7f93ee25470c4ffd1fdc2aa964"].pack("H*")
salt = ["83237eac0f5bb1cfa98d54b00c7057820843b8f0ca390edc7f6b99138cb14937"].pack("H*")

url = "https://items.epicpxls.com/shrine/cache/6022d511fb12d7cd28b90bf27bdad710.gif"

# You can trim padding spaces to get good-looking url
encoded_url = Base64.urlsafe_encode64(url).tr("=", "").scan(/.{1,16}/).join("/")

resize = "fill"
width = 300
height = 300
gravity = "no"
enlarge = 1
extension = "gif"

path = "/#{resize}/#{width}/#{height}/#{gravity}/#{enlarge}/#{encoded_url}.#{extension}"

digest = OpenSSL::Digest.new("sha256")
# You can trim padding spaces to get good-looking url
hmac = Base64.urlsafe_encode64(OpenSSL::HMAC.digest(digest, key, "#{salt}#{path}")).tr("=", "")

signed_path = "https://epicpxls-imgproxy.herokuapp.com/#{hmac}#{path}"
print signed_path
```

It works if i give it a png image. https://epicpxls-imgproxy.herokuapp.com/HHWO2-IeiDKYeJJamEmZ8UvAg2SNFF7v_En-3895il8/fill/300/300/no/1/aHR0cHM6Ly9pdGVt/cy5lcGljcHhscy5j/b20vdXBsb2Fkcy9w/aG90by82NTY4ZDU2/YjU4MTgwYWViMTY0/NWUxMWVhNGNjYmRi/OS5wbmc.png

```ruby
require "openssl"
require "base64"

key = ["c84285e0bec255fe163410fcedfe61e256f04a7f93ee25470c4ffd1fdc2aa964"].pack("H*")
salt = ["83237eac0f5bb1cfa98d54b00c7057820843b8f0ca390edc7f6b99138cb14937"].pack("H*")

url = "https://items.epicpxls.com/uploads/photo/6568d56b58180aeb1645e11ea4ccbdb9.png"

# You can trim padding spaces to get good-looking url
encoded_url = Base64.urlsafe_encode64(url).tr("=", "").scan(/.{1,16}/).join("/")

resize = "fill"
width = 300
height = 300
gravity = "no"
enlarge = 1
extension = "png"

path = "/#{resize}/#{width}/#{height}/#{gravity}/#{enlarge}/#{encoded_url}.#{extension}"

digest = OpenSSL::Digest.new("sha256")
# You can trim padding spaces to get good-looking url
hmac = Base64.urlsafe_encode64(OpenSSL::HMAC.digest(digest, key, "#{salt}#{path}")).tr("=", "")

signed_path = "https://epicpxls-imgproxy.herokuapp.com/#{hmac}#{path}"
print signed_path
```

Thanks in advance. :)

**Comment by Chocksy** [comment]
I can confirm that the heroku app was made with the docker image:
```
=== Fetching app code
Sending build context to Docker daemon  23.12MBStep 1/9 : FROM alpine:edge
edge: Pulling from library/alpine
1eae7a7426b0: Pulling fs layer
1eae7a7426b0: Verifying Checksum
1eae7a7426b0: Download complete
1eae7a7426b0: Pull complete
Digest: sha256:79c2c5f6db53da44f90bb2731f29f725b5b14c378407a123776b6d3c76e6aebe
Status: Downloaded newer image for alpine:edge
```

**Comment by DarthSim** [comment]
Provided image URL works for me:

![](https://epicpxls-imgproxy.herokuapp.com/HHWO2-IeiDKYeJJamEmZ8UvAg2SNFF7v_En-3895il8/fill/300/300/no/1/aHR0cHM6Ly9pdGVt/cy5lcGljcHhscy5j/b20vdXBsb2Fkcy9w/aG90by82NTY4ZDU2/YjU4MTgwYWViMTY0/NWUxMWVhNGNjYmRi/OS5wbmc.png)

BTW, libvips doesn't work properly with animated GIFs, and imgproxy doesn't support GIF output, so only the first frame of GIF will be processed.

**Comment by Chocksy** [comment]
Yeah the link i provided was for the png test that works. Ok if gif is not supported then it's understandable. So it should just work for non animated gifs i guess. That's a bummer as i would have really loved this. My server struggles with resizing animated gifs and in the end i even stoped doing it. :(
