### ISSUE TITLE
Version 1.1.x no longer respects http_proxy

### ISSUE THREAD

**Issue by SxDx** [DarthSim/imgproxy#49]
After upgrading from Version 1.0 to Version 1.1.1 I noticed that
imgproxy no longer worked for me because it ignores the http_proxy ENV 
variables.

I had a look a the changes and it seems either the updated go version or https://github.com/DarthSim/imgproxy/blob/28d5784c03c1476006dc72a754b39e0cfb492363/download.go#L59 seems to be the problem.

**Comment by DarthSim** [comment]
Fixed in 1.1.2. Please check.

**Comment by SxDx** [comment]
I can confirm 1.1.2 restores Proxy support, thank you.
