### ISSUE TITLE
Feature request : Relative URLs

### ISSUE THREAD

**Issue by julienbornstein** [DarthSim/imgproxy#55]
Feature request : Add ENV VAR to configure an _URL Base Path_ that will be prepend to the given url, so we can pass a relative url (and hide the full url to users)

Exemple : 
- source image (part that is encoded in imageproxy request) : /cats/meow.jpg 
- ENV_VAR : URL_BASE_PATH="https://s3bucket/images"

imageproxy concat everything and get the full image source url at  https://s3bucket/images/cats/meow.jpg

**Comment by DarthSim** [comment]
HI.
I'm very sorry for the long period of inactivity.

The feature is implemented in the latest release
