### ISSUE TITLE
Feature Request: Content Length header

### ISSUE THREAD

**Issue by daneren2005** [DarthSim/imgproxy#56]
Right now the server is not responding with a content length header.  I don't really know much Go, but looking at https://github.com/DarthSim/imgproxy/blob/master/server.go#L108 it looks like you have the entire image at the time of setting the headers, so it should be possible to add the content length as a header.

**Comment by DarthSim** [comment]
HI.
I'm very sorry for the long period of inactivity.

Content-Length was added to the latest release.

**Comment by xtagon** [comment]
Thank you for adding this 👍
