### ISSUE TITLE
Feature Request: Rotation only

### ISSUE THREAD

**Issue by daneren2005** [DarthSim/imgproxy#57]
I want to be able to turn off the enlarge option, but I depend on the images being rotated according to their EXIF data.

ie: If I have a 300 x 300 image, and want a 500 x 500 thumbnail, I want to be able to turn enlarge off so that ImgProxy will still serve a 300 x 300 image.  If that image has EXIF rotation, I still need the EXIF rotation to be applied in what is served to the client.

**Comment by xtagon** [comment]
This is desirable for me as well. The use case is showing a full-sized image preview but taking advantage of imgproxy to handle EXIF orientation (since browsers are all finicky about that and behave differently).

**Comment by DarthSim** [comment]
Hi!
Actually, this is not a feature request but bug request :) Thanks for catching one! Fixed in the latest release.
