### ISSUE TITLE
Specifying only height and calculating width from source ratio

### ISSUE THREAD

**Issue by dimamedvedev** [DarthSim/imgproxy#61]
Hey, we've hacked a feature to only specify height and calculate width based on source image h/w ratio. It breaks a bit of standard logic though. Are you interested in this?

**Comment by DarthSim** [comment]
Hi Dima,

We use a dirty hack for the similar need (fixed width, various height): specify the desired width and an "impossible" height with `fit` resize algorithm. 300x9999999 for example. If the image doesn't have a huge aspect ratio, it will always be resized to the width of 300. In your case, you should specify desired height and "impossible" width.

Anyway, if you have a solution for this, I'd like to check it out. PRs are always welcome :)
