### ISSUE TITLE
Huge image: Image is unreachable error

### ISSUE THREAD

**Issue by afitiskin** [DarthSim/imgproxy#63]
Image: https://dev-swm.s3.eu-central-1.amazonaws.com/2xYmnilMgPbQZYY1PqLFf6tbkPelI8zS7gDm1ebo/1531219616_original.jpeg (~5mb)

Imgproxy: https://myimgproxy.herokuapp.com/ (deployed via "Deploy to heroku" button)
Key: c84285e0bec255fe163410fcedfe61e256f04a7f93ee25470c4ffd1fdc2aa964
Salt: 83237eac0f5bb1cfa98d54b00c7057820843b8f0ca390edc7f6b99138cb14937

Trying to resize to 1600x1200 (fit)
Making URL via imgproxy URL generator (https://progapandist.github.io/imgproxy-form/)

Result URL: https://myimgproxy.herokuapp.com/w2-4-QSxqdS-W2H0G6IWNGIVwPKZM6cWvDkpLab8n4A/fit/1600/1200/no/0/aHR0cHM6Ly9zMy5ldS1jZW50cmFsLTEuYW1hem9uYXdzLmNvbS9kZXYtc3dtLzJ4WW1uaWxNZ1BiUVpZWTFQcUxGZjZ0YmtQZWxJOHpTN2dEbTFlYm8vMTUzMTIxOTYxNl9vcmlnaW5hbC5qcGVn.jpg

Response is 404 Image is unreachable.

PS. Other images from same s3 bucket are processed normally, e.g.:
Image: https://dev-swm.s3.eu-central-1.amazonaws.com/TgMxlLItXzeM4iuzYWieVIjxAuMzCFpR4YWhlwgh/1526312072_original.jpeg
Result URL: https://myimgproxy.herokuapp.com/ZjuJk0aYaCeRiu6azS6UpT3b8HVZkyF2xfIeptYQMow/fit/1200/1600/no/0/aHR0cHM6Ly9kZXYtc3dtLnMzLmV1LWNlbnRyYWwtMS5hbWF6b25hd3MuY29tL1RnTXhsTEl0WHplTTRpdXpZV2llVklqeEF1TXpDRnBSNFlXaGx3Z2gvMTUyNjMxMjA3Ml9vcmlnaW5hbC5qcGVn.jpg

**Comment by DarthSim** [comment]
Hi Alex,

HTTP response contains a message for the user. It doesn't represent all the situation.
In your case image is 10000x5652. This size doesn't pass any of size checks, and imgproxy declines it. Take a look at https://github.com/DarthSim/imgproxy#security-1

**Comment by afitiskin** [comment]
Thank you @DarthSim. It would be great if HTTP response text or header contains some error code or message that describe why imgproxy decline image processing...

**Comment by DarthSim** [comment]
I don't think a user should know the details. For the details take a look at the logs, all interesting things live there :)
