### ISSUE TITLE
allow to specify Etag random value

### ISSUE THREAD

**Issue by josepowera** [DarthSim/imgproxy#67]
In console we see message:
2018/08/31 10:29:23 ETag support is activated. The random value was generated to be used for ETag calculation: c0fd3d0196c3209049f6dcf76af47226

It would be great to be able to specify Etag Random value in program startup using parameters/ env variables.

Reason: 
If we run multiple instances we would like to have same Etag from every imgproxy running. If value is random generated on program start, the http ETAG signature header will change for every instance of imgproxy running.

**Comment by DarthSim** [comment]
Hi!

This will break the whole idea of that random value. Instead of it, I got rid of the random value at all. Now imgproxy uses current config and version instead of it. Check out the latest release.
