### ISSUE TITLE
Accept Header support this time maybe?

### ISSUE THREAD

**Issue by MarcBoeing** [DarthSim/imgproxy#68]
Hi Sergey,

as you are actively working on version 2.0 I´d like to kindly ask if you could (again) think about implementing accept header support. I believe some of the other closed issues #4 and #23 had the same wish:
Providing jpg and webp over one URL based on browser support with the advantage of saving space in the picture element (or whatever others use) plus dynamically provide the best possible image.

I understand the danger of DDos but see two options:
1) enable it through env var and leave it disabled as default
2) dropping invalid headers in cdn (if supported) or nginx reverse proxy config to not reach imgproxy

Thank you and best regards
Marc

**Comment by DarthSim** [comment]
Hi Marc!

I definitely can't reject this request the third time :) Especially while crafting All-You-Ever-Wanted version of imgproxy.

I can and I will add this feature to 2.0, but every user should understand its cons and dangers.

**Comment by DarthSim** [comment]
:tada: imgproxy v2.0 has been released :tada: Take a look at the new features, including WebP support detection: https://github.com/DarthSim/imgproxy/blob/master/CHANGELOG.md#v200
