### ISSUE TITLE
Allow disabling signatures

### ISSUE THREAD

**Issue by ishitatsuyuki** [DarthSim/imgproxy#69]
As I run imgproxy behind the main application server to apply authorization, there's not much point in signing it. It's both coding and runtime overhead, so can we make it optional?

**Comment by DarthSim** [comment]
Hi! This is the part of v2.0 that will be released soon.

**Comment by DarthSim** [comment]
:tada: imgproxy v2.0 has been released :tada: Take a look at the new features, including disabling signature checking: https://github.com/DarthSim/imgproxy/blob/master/CHANGELOG.md#v200
