### ISSUE TITLE
Background colour for jpegs

### ISSUE THREAD

**Issue by znar** [DarthSim/imgproxy#70]
Hello, it would be helpful if it would be possible to set the background color for jpges when creating them from image types with alpha channel.

**Comment by DarthSim** [comment]
Hi! This is the part of v2.0 that will be released soon.

**Comment by znar** [comment]
Thank you very much, this ist a big issue for us :)

**Comment by DarthSim** [comment]
:tada: imgproxy v2.0 has been released :tada: Take a look at the new features, including background colour: https://github.com/DarthSim/imgproxy/blob/master/CHANGELOG.md#v200
