### ISSUE TITLE
Question. How does CGO import methods from vips/operation.h?

### ISSUE THREAD

**Issue by volyx** [DarthSim/imgproxy#71]
Example:

There is call of method `C.vips_cache_set_max_mem(0)` https://github.com/DarthSim/imgproxy/blob/master/process.go#L103

But it is not declared in vips.h(https://github.com/DarthSim/imgproxy/blob/master/vips.h)
and in libvips headers files(vips/vips.h, vips/vips7compat.h)

This method is here - https://github.com/libvips/libvips/blob/master/libvips/include/vips/operation.h

How does CGO import it?

**Comment by DarthSim** [comment]
`vips/vips.h` includes `vips/operation.h` https://github.com/libvips/libvips/blob/master/libvips/include/vips/vips.h#L133
