### ISSUE TITLE
imgproxy 2.0.0 - Invalid token cause of url parameter

### ISSUE THREAD

**Issue by MarcBoeing** [DarthSim/imgproxy#72]
Hi DarthSim,

I just tested version 2.0.0 on our staging system and it only produces "Invalid token" errors.
It looks like version 2.0.0 now uses url parameters to calculate the Token.

version 1.1.8:
CfcihlU34vwExBCyL7m2Ojmyw4K13Y3cioWttti6yN4/fit/2330/1185/no/1/bG9jYWw6Ly8vY21zL2Ntcy41YTNiOGI4YjQ1MTQ0MC4xNDI2OTUzNi5qcGVn.webp => works
CfcihlU34vwExBCyL7m2Ojmyw4K13Y3cioWttti6yN4/fit/2330/1185/no/1/bG9jYWw6Ly8vY21zL2Ntcy41YTNiOGI4YjQ1MTQ0MC4xNDI2OTUzNi5qcGVn.webp?32256495 => works

version 2.0.0
CfcihlU34vwExBCyL7m2Ojmyw4K13Y3cioWttti6yN4/fit/2330/1185/no/1/bG9jYWw6Ly8vY21zL2Ntcy41YTNiOGI4YjQ1MTQ0MC4xNDI2OTUzNi5qcGVn.webp => works
CfcihlU34vwExBCyL7m2Ojmyw4K13Y3cioWttti6yN4/fit/2330/1185/no/1/bG9jYWw6Ly8vY21zL2Ntcy41YTNiOGI4YjQ1MTQ0MC4xNDI2OTUzNi5qcGVn.webp?32256495 => doesn´t work

Is this the new default behavior?

Best regards
Marc

**Comment by DarthSim** [comment]
Hi Marc,

Sorry for this bug. I don't use URL params, so I have missed it while I was changing `net/http` to `fasthttp`. I rebuilt v2.0.0 image with the fix.

**Comment by MarcBoeing** [comment]
Yes works, thank you!

**Comment by DarthSim** [comment]
Thank you for catching this! :)
