### ISSUE TITLE
Question. Why do we need vips.h and image_type.h in project? 

### ISSUE THREAD

**Issue by volyx** [DarthSim/imgproxy#74]
We could write this functions in process.go file in Go. What the reason?

**Comment by DarthSim** [comment]
There are many reasons:

1. libvips functions take unlimited arguments, and Go can't call this kind of functions with cgo. So I wrapped 'em in `*_go` functions that take only those arguments I need.
2. Some functions in `vips.h` have different behaviour depends on libvips version. It's compile-time check, and it's more usable on C side.
3. Defining image types on C side is a way to ensure they're the same on both C side and Go side.
