### ISSUE TITLE
Watermark

### ISSUE THREAD

**Issue by julienbornstein** [DarthSim/imgproxy#76]
Hi, it would be nice to add image watermark support. Exemple : https://docs.spatie.be/image/v1/image-manipulations/watermarks

**Comment by DarthSim** [comment]
Hi!
Watermarks support was implemented in [v2.1 branch](https://github.com/DarthSim/imgproxy/tree/version/2.1). If you don't mind of using beta-versions, you can pull [official Docker image](https://hub.docker.com/r/darthsim/imgproxy/tags/) with tag `v2.1.0.beta1`. Check out [watermarks guide](https://github.com/DarthSim/imgproxy/blob/version/2.1/docs/watermark.md) for more info.

**Comment by julienbornstein** [comment]
Working great ! Maybe you can add watermark size option ?

**Comment by DarthSim** [comment]
Well, this will affect performance, but I think you know what you're asking for :)
Let's discuss this. We need to come up with a simple way to specify a watermark size. Could you describe the desired functionality here?

**Comment by julienbornstein** [comment]
Sure.

Just an example :
* I have a photo, original size : 2000x1500 px
* My watermark is a rectangle image : 500x250 px
* I want to resize the original image in two size : 1600x1200 px and 800x600 px
* I need that ratio picture / watermark keep the same, 10% of the width (10% is just an example)

So the size of the watermark for the 1600x1200 photo will be 160x80px, and the watermark size for the 800x600px should be 80x40px.

So using the advanced URL format, it could be something like that :
wm:%width:%height:%opacity:%position:%x_offset:%y_offset

So in the example case, url formats will be : 
wm:160:80:1:soea:10:10 and wm:80:40:1:soea:5:5

**Comment by julienbornstein** [comment]
Maybe instead of giving width and height, we can pass a scale value as Cloudimage do it : 
https://docs.cloudimage.io/go/cloudimage-documentation/en/static-watermark/

Imgix has both options, scale and width/height : 
https://docs.imgix.com/apis/url/watermark/markpad

Scale value is easier, no calculation client side. Watermark resizing calculation is done server side
Width & Height is more flexible (but why someone would like to change the watermark ratio ?)

**Comment by DarthSim** [comment]
I love the idea of scale, so I added it as the last argument: 
```
watermark:%opacity:%position:%x_offset:%y_offset:%scale 
```
`scale` is a floating point number that defines watermark size relative to the resulting image size. When set to 0 or omitted, watermark size won't be changed.

Docker image `v2.1.0.beta2` includes this change and also fixes a critical bug, so I highly recommend to update.

**Comment by julienbornstein** [comment]
Working perfecty ! 👍 I'm going to deploy in production soon.

Just want to talk about an issue in the implementation : the watermark source image is not part of the url and so If user change the watermark source image, the url still remain the same and will not be refresh by CDNs. The watermark won't change until cache expiration.
How to fix it ? : maybe the watermark image source should be included in the url and not from the ENV vars ? Or maybe we could append a cache busting value to the url depending of the watermark image data. The value could be the hash of the watermark image, or whatever... 
`watermark:%source_image:%opacity:%position:%x_offset:%y_offset:%scale`
or
`watermark:%opacity:%position:%x_offset:%y_offset:%scale:%cache_busting_value`

What do you think about this ?

**Comment by DarthSim** [comment]
Good point! I think, the cache buster shouldn't be a part of the watermark option, because the issue affects some other things like presets or quality settings. I created a new issue about cache buster #84.

Since you look happy with watermarks, I close this issue.

**Comment by DarthSim** [comment]
Just released imgproxy v2.1.0 with this and other awesome features. Check out the changelog for details: https://github.com/DarthSim/imgproxy/blob/master/CHANGELOG.md#v210
