### ISSUE TITLE
Feature: Add /health route

### ISSUE THREAD

**Issue by Lord-Y** [DarthSim/imgproxy#78]
Hi there,

It can be useful to have a /health route to know it everything is working perfectly. Need it for Kubernetes check. When checking only / , the pod return an HTTP 404 error so I got to use and another trick in Kubernetes health check like livenessProbe/readinessProbe exec command checking `/usr/local/bin/imgproxy` exists.

**Comment by DarthSim** [comment]
Hi,
imgproxy has a `/health` endpoint. https://github.com/DarthSim/imgproxy/blob/master/docs/healthcheck.md
