### ISSUE TITLE
New Relic Metrics

### ISSUE THREAD

**Issue by bonafernando** [DarthSim/imgproxy#79]
imgproxy could have an option to send metrics to New Relic.

**Comment by DarthSim** [comment]
Hi!
New Relic metrics support was implemented in [v2.1 branch](https://github.com/DarthSim/imgproxy/tree/version/2.1). If you don't mind of using beta-versions, you can pull [official Docker image](https://hub.docker.com/r/darthsim/imgproxy/tags/) with tag `v2.1.0.beta1`. Check out [New Relic guide](https://github.com/DarthSim/imgproxy/blob/version/2.1/docs/new_relic.md) for more info.

**Comment by DarthSim** [comment]
Just released imgproxy v2.1.0 with this and other awesome features. Check out the changelog for details: https://github.com/DarthSim/imgproxy/blob/master/CHANGELOG.md#v210
