### ISSUE TITLE
Consider larger default limits

### ISSUE THREAD

**Issue by homm** [DarthSim/imgproxy#8]
Even regular (not panoramas) photos from iPhone (which is not the highest-resolution camera on the market) have 4032 × 3024 resolution nowadays. Consider increasing default limits.

Another suggestion: you have limits for maximum dimension. Let's assume that I want to support panorama photos from iPhone. Their resolution is up to 16382 × 3932 pixels which is about 64 megapixels. So I have to set `IMGPROXY_MAX_SRC_DIMENSION` to 16382. This unleashes sources up to 268 megapixels, which is totally crazy. So I suggest limiting source resolution instead of dimensions. In this case, I will be able to set `IMGPROXY_MAX_SRC_RESOLUTION` to 65MP and get the desired behaviour.

**Comment by oldcai** [comment]
Yes, and another problem appeared: by now, more and more needs and parameters are added to the request, the `/%signature/%resizing_type/%width/%height/%gravity/%enlarge/%encoded_url.%extension` format doesn't seem capable of taking too many parameters if not extended too long.
I think a default config can be set and we only need to set size and sometimes set other parameters by keywords.

**Comment by bscott** [comment]
Created a first pass pull request #22

**Comment by homm** [comment]
Copy here to not lose:

I don't know VIPS internals but for some libraries, this does sense, because too tall or too wide images (for example 1x15000000) can have some overhead in processing and this could be used as a vulnerability.

I suggest setting the max resolution to some suitable value, like 15M and set the max dimension to a high, but realistic value like 16K or 32K.

**Comment by DarthSim** [comment]
Here it comes! https://github.com/DarthSim/imgproxy/commit/2940478ec9ef298129a6e6df1c58e688cd03c478
I increased default max dimension to 8192^ and added max resolution config which is 16.8 by default.
