### ISSUE TITLE
Support for capitalised file extensions

### ISSUE THREAD

**Issue by adamquaile** [DarthSim/imgproxy#83]
We have some image URLs ending in `.JPG`. This results in `Invalid image format: JPG`. 

It looks like it's coming from https://github.com/DarthSim/imgproxy/blob/master/image_types.h and https://github.com/DarthSim/imgproxy/blob/f5f6b24d4b19a20dffd08205181a67e7b3dde3e5/processing_options.go#L424 . 

Would lowercasing the extension in this function be enough to add support for this? 

Thanks

**Comment by DarthSim** [comment]
Hi,

I'm not a fan of modifying processing options without significant need. Is there a reason why you can't use lowercased extension in processing options? Extension of the source image and resulting one have nothing common.

**Comment by adamquaile** [comment]
Hi, 

For our particular situation, we have the images hosted on s3, uploaded through strapi (a cms). Since we can't control what a user's browser sends as the filename on upload, we can either modify strapi to lowercase the files before sending to s3, or modify imgproxy to not fail when it receives a request with an uppercase filename. 

I'm not sure whether the location in processing_options I've mentioned is the correct place to make a change like that (and I'm not a go developer). 

Since as you say "Extension of the source image and resulting one have nothing common." it seemed odd that it would fail processing an image with a `.JPG` extension and like the fix would be within imgproxy rather than strapi. If you'd prefer not to for whatever reason, we'll find a workaround though. 

Thanks!

**Comment by adamquaile** [comment]
Ah, yeah. I misunderstood how this was working (I did think it was strange imgproxy was relying on the extension like this). 

In this case, we can certainly fix this ourselves. 

Thanks for your help.
