### ISSUE TITLE
quality of the resulting image, arg in url (if not: default)?

### ISSUE THREAD

**Issue by russelgal** [DarthSim/imgproxy#85]
`resize:%resizing_type:%width:%height:%enlarge`

`resize:%resizing_type:%width:%height:%enlarge:%quality`

**Comment by russelgal** [comment]
#§

**Comment by selul** [comment]
hello, 

just an idea if you would like to consider, as imgproxy is already using the Accept header for switching to WebP when possible, do you think it could be a good idea to fetch the quality factor from the header too -> https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept,  when the quality is missing from the URL or is using some value of `auto` ? 
As a fallback, it could always switch to the env variable. 

I've been using it on optimole.com which is powered by a slightly modified version of imgproxy and i would be happy to contribute if you need any help. 

Thanks a lot for your hard work.

**Comment by DarthSim** [comment]
This feature has been released in `v2.1.0.rc1`. https://github.com/DarthSim/imgproxy/blob/version/2.1/docs/generating_the_url_advanced.md#quality

**Comment by DarthSim** [comment]
Just released imgproxy v2.1.0 with this and other awesome features. Check out the changelog for details: https://github.com/DarthSim/imgproxy/blob/master/CHANGELOG.md#v210
