### ISSUE TITLE
Configure user agent

### ISSUE THREAD

**Issue by twarkie** [DarthSim/imgproxy#86]
Hi!

I'm currently using imgproxy in production and it works great...mostly. A couple of our external sources seems to block requests without a user agent, or at least without a normal browser user agent.

Would it be possible to add a config variable for user agent?

**Comment by DarthSim** [comment]
This feature has been released in v2.1.0.rc1. Now you can use `IMGPROXY_USER_AGENT` env variable to specify user agent.

**Comment by DarthSim** [comment]
Just released imgproxy v2.1.0 with this and other awesome features. Check out the changelog for details: https://github.com/DarthSim/imgproxy/blob/master/CHANGELOG.md#v210
