### ISSUE TITLE
404 error when Serving local files

### ISSUE THREAD

**Issue by tianjoey** [DarthSim/imgproxy#87]
I try to serving local files with imgproxy, but I get 404 error just like below.
I set IMGPROXY_LOCAL_FILESYSTEM_ROOT with /data.

**Get local:///pic/f19c38286b4c8c356c1aaa6a9958a6c9.png: unsupported protocol scheme "local"**

**Comment by DarthSim** [comment]
Hi,
Could you ensure that there is no typo in `IMGPROXY_LOCAL_FILESYSTEM_ROOT`? Looks like imgproxy didn't enable local protocol. This happens when `IMGPROXY_LOCAL_FILESYSTEM_ROOT` is blank.

**Comment by DarthSim** [comment]
The issue looks abandoned. Hope you managed to solve the problem.

**Comment by javeedrahman** [comment]
Hi @DarthSim ,

I am trying to set SERVING file local 

docker run -p 8080:8080 -e IMGPROXY_LOCAL_FILESYSTEM_ROOT="/home/test/images" -it darthsim/imgproxy

and i am getting this below
FATAL   [2020-07-17T11:03:33Z] Cannot use local directory: stat /home/test/images: no such file or directory

**Comment by DarthSim** [comment]
@javeedrahman That's because Docker doesn't see your local filesystem. That's one of the containerization cornerstones. You need to mount your local directory to your Docker container. Try this:

```
docker run -p 8080:8080 -v "/home/test/images:/images" -e IMGPROXY_LOCAL_FILESYSTEM_ROOT="/images" -it darthsim/imgproxy
```

**Comment by Aleksandr-Kalinichenko** [comment]
> @javeedrahman That's because Docker doesn't see your local filesystem. That's one of the containerization cornerstones. You need to mount your local directory to your Docker container. Try this:
> 
> ```
> docker run -p 8080:8080 -v "/home/test/images:/images" -e IMGPROXY_LOCAL_FILESYSTEM_ROOT="/images" -it darthsim/imgproxy
> ```

what will be the path to the image?

**Comment by DarthSim** [comment]
@Aleksandr-Kalinichenko In the described case, if your image is located at `/home/test/images/some/image.png`, you should use `local:///some/image.png` as the source URL.
