### ISSUE TITLE
support for client hints ? 

### ISSUE THREAD

**Issue by selul** [DarthSim/imgproxy#92]
Hi, 

Do you think will be useful to integrate Client hints https://developers.google.com/web/updates/2015/09/automating-resource-selection-with-client-hints into imgproxy ? 

Something like when the width&height is missing from the url, processing options will consider the `Width` header, or if this is not present, `Viewport-Width` header? 

Related to this it might be useful to have a DPR processing option ? 

I've been able to implement those into optimole.com, which is using a slightly modified version of imgproxy, i would be happy to contribute if you need any help. 

Thanks a lot for your hard work !

**Comment by DarthSim** [comment]
Hi,

I think about headers as a dangerous territory since they can't be signed. An attacker will be able to spam your imgproxy by changing `Viewport-Width` header. They also can eat all your memory by sending a huge number in `Viewport-Width`. How do you deal with it in OptiMole?

Regarding DPR option, how is it different from just requesting a bigger size?

**Comment by selul** [comment]
Thanks for the feedback, @DarthSim.

Indeed is on the gray area but when the URL is unsigned, wont make any difference i think, as I was using those headers as defaults in the processing option func and the same normalizations will apply during the process as the width used as an argument in the URL.

Regarding DPR transformation I find it handy when you want to multiply the resulting image size by a certain factor. 

Moreover, when you don't know what size the resulting image will have, i.e width/height is not passed as arguments, this is very useful to format images for HiDPI devices.

**Comment by selul** [comment]
I've just added a PR https://github.com/DarthSim/imgproxy/pull/94, I would love to hear your thoughts.

**Comment by DarthSim** [comment]
Done with #98
