### ISSUE TITLE
Support key and salt rotating

### ISSUE THREAD

**Issue by itsliang** [DarthSim/imgproxy#93]
If I want to change the key and/or salt in production environment (maybe 3 imgproxy servers behind a load balancer), it is very crucial not to stop the service. I found it seems difficult to achieve this requirement. If I change key/salt in my application first, I cannot get imgproxy to process the image for me any more. Likewise if I change key/salt in imgproxy first.

I wonder to know if it is possible to store an array in IMGPROXY_KEY and IMGPROXY_SALT. Here is the example:

IMGPROXY_KEY: ["key1", "key2", ...]
IMGPROXY_SALT: ["salt1", "salt2", ...]

With this kind of settings, imgproxy can check the signature with key1/salt1 first, if it failed, continue to check with key2/salt2. And now it is safe to update each server's key/salt one by one without breaking any service.

**Comment by DarthSim** [comment]
Hi,

Is there any significant reason to change key/salt pair so often?

To be honest, I don't like the idea, because it's like setting multiple passwords to DB.

**Comment by itsliang** [comment]
Normally I won't change key/slat often, currently only under two circumstances I need to change the key/salt. The first one is to obey my company's audit policy, I have to change key/salt once every year. The second one is when I observed a suspicious activity.

The solution I proposed was referenced from https://cloud.google.com/kms/docs/rotating-keys, but simplified. I think I can live with any kind of solutions, no matter is it key rotating based. The only requirement is to keep my imgproxy service with zero down time when changing key and/or salt.

**Comment by selul** [comment]
Maybe a fail-safe approach will work in this case?  Something like, if the signature is not valid, redirect to the original image URL? I think it's better than showing the error message?

**Comment by itsliang** [comment]
@selul How do I know if the signature is invalid? I just generate a key and give the same key to both imgproxy and my application. If I generate a new key and update the key in my application first, my application will still generate signature fine without error. I won't know whether the signature is valid.

Or do you mean I have to check every image returned by imgproxy to see if it is empty (or error, or not found)? And if it is empty, redirect to original image. This maybe doable, but I think this is cumbersome. If I have a lot of images on my web page, I wonder to know if this will slow down the page loading. Furthermore, this solution will skip the CDN cache, if the original images are pulled from my own website, this will definitely slow down the website, or worse, paralyzed it.

**Comment by selul** [comment]
@itsliang I might misunderstand your problem, if so please ignore my reply. 
I thought you are worried that the URLs of the images generated with the old keys/salt won't work after you deploy the new one's credentials. 

In that case, I was thinking that, if imgproxy detects an invalid token error, don't display the error message and rather redirect to the original image. Yes, this will slow down the website where you use the images, but this is temporary until you will replace the images URLs with the new signature.

**Comment by itsliang** [comment]
@selul Thanks for your suggestion. But I think this approach is a little bit unsafe, because the using of signature is to prevent my imgproxy being used by other people. If imgproxy redirects requests to original image when signature check failed, my imgproxy might be used by malicious software.

**Comment by DarthSim** [comment]
Well, though I still don't really like the idea, it's pretty easy to implement. `v2.1.0.rc2` (available on Docker Hub) allows specifying multiple keys and salts divided by comma (`,`).

**Comment by DarthSim** [comment]
Just released imgproxy v2.1.0 with this and other awesome features. Check out the changelog for details: https://github.com/DarthSim/imgproxy/blob/master/CHANGELOG.md#v210
