### ISSUE TITLE
Source image resolution are too big

### ISSUE THREAD

**Issue by Lord-Y** [DarthSim/imgproxy#96]
Hi,

I'm trying to figure out how to be able to resize this kind of image. I tried to change IMGPROXY_MAX_SRC_RESOLUTION parameter but I still getting `Source image resolution are too big` in docker image log.

![image](https://user-images.githubusercontent.com/8832734/47885114-d13e0080-de33-11e8-9806-a081f008cd09.png)

Any help?

PS: I tried docker version v2.0.2 and v2.1.0.beta2

**Comment by itsliang** [comment]
This is not an issue. It depends on your need and how you configure your imgproxy server. What is your new value of IMGPROXY_MAX_SRC_RESOLUTION?

According to your image width and height, the resolution is 5002 * 3654 = 18277308 (you can find this number in "Number of pixels" as well). It can be translated into 18.2 mega pixel, which means you have to configure your IMGPROXY_MAX_SRC_RESOLUTION above this value.

**Comment by DarthSim** [comment]
Hi,

Yep, @itsliang is totally right. Check out the docs for more info: https://github.com/DarthSim/imgproxy/blob/master/docs/configuration.md#security

**Comment by Lord-Y** [comment]
In my docker compose I put `IMGPROXY_MAX_SRC_RESOLUTION="20"` instead of `IMGPROXY_MAX_SRC_RESOLUTION=20`that why it wasn't working. My bad!

**Comment by gpapin** [comment]
Is there a way to disable this setting ?

**Comment by DarthSim** [comment]
@gpapin Just set `IMGPROXY_MAX_SRC_RESOLUTION` to some unrealistic value like `9999`.

**Comment by gpapin** [comment]
I was thinking something like `-1` but I guess that would do the job too 😅 
(For anyone reading this, I tried `-1` and that doesn't work)

**Comment by kristian-nst** [comment]
I'm encountering this issue also. We don't have `IMGPROXY_MAX_SRC_RESOLUTION` set in env. The default is 50, and our image is ~22 MP 🤔 

![Image](https://github.com/user-attachments/assets/3547eb01-35d4-4cd5-a7ea-0815b52a223a)

**Comment by DarthSim** [comment]
@kristian-nst Which version do you use?

**Comment by kristian-nst** [comment]
Hey. Latest Docker image.

I'm not quite sure what was wrong., but seems we were using Helm, and this helped:
```
    security:
      # the maximum resolution of the source image, in megapixels. Images with larger actual size will be rejected.
      maxSrcResolution: "100"
```

Tho, not sure why the default of 50 didn't work :)

**Comment by DarthSim** [comment]
@kristian-nst Oh, that's because the Helm chart has its own defaults 😓 I discussed this with its devs, and your case will be a good example of why we should remove them 🙂

**Comment by kristian-nst** [comment]
> @kristian-nst Oh, that's because the Helm chart has its own defaults 😓 I discussed this with its devs, and your case will be a good example of why we should remove them 🙂

Cool. Thanks for answering 😃
