### ISSUE TITLE
Make white the default background color

### ISSUE THREAD

**Issue by brandonkal** [DarthSim/imgproxy#99]
Using a white background is more natural when converting PNGs with transparency to JPEG format.
Black is more jarring.

I do realize an option exists for this, but white should be the default as it will give a closer representation of "transparency" when viewed on a white screen or print medium. This is especially useful if text is present in an image. On the otherhand, white-on-black layouts are now quite rare.

**Comment by daneren2005** [comment]
You mention that there is an option for this.  I didn't see it anywhere.  Where can I specify to do white backgrounds instead of black?

**Comment by brandonkal** [comment]
@daneren2005 https://github.com/DarthSim/imgproxy/blob/master/docs/generating_the_url_advanced.md#background

**Comment by daneren2005** [comment]
Oh I see.  I was looking for a env variable and not part of the advanced url schema (I am still using the simple legacy urls) at the moment.

**Comment by DarthSim** [comment]
Well, this makes sense. `v2.1.0.rc2` flattens `jpg` output with white by default. `v2.1.0.rc2` is available on Docker Hub.

**Comment by DarthSim** [comment]
Just released imgproxy v2.1.0 with this and other awesome features. Check out the changelog for details: https://github.com/DarthSim/imgproxy/blob/master/CHANGELOG.md#v210
